#!/usr/bin/env bash
# verify.sh — deterministic web-UI verifier (UI-1). Mirrors hardware-verify/verify.sh.
# ZERO-LLM here: detect frontend stack, probe optional Playwright MCP, §6.4 lint, parse the
# per-target browser success contract, emit a tri-state verdict. The real browser_* reads are
# done by the dispatched provider-agnostic ui-vision-judge (the configured vision provider, §4.5) — §7.3 PENDING-VERIFY.
#
# MCP probe (§5): `timeout <s> claude mcp list`, parse SE16-safe (case-glob, never |grep -q).
#   claude absent / timeout / probe error => mcp-present:no => UI-UNVERIFIED (never hang/crash/PASS).
#   SDLC_PLAYWRIGHT_MCP=1|0 overrides the probe (TEST stub only — not set by any prod harness).
# Exit: 0 PASS or UI-UNVERIFIED-WARN · 2 usage/not-a-web-app · 3 FAIL · 4 unreachable ·
#       5 --require-mcp & MCP absent · 6 §6.4 lint · 7 contract absent/trivial/stale-evidence.
set -uo pipefail

repo="$PWD" criteria="" url="" health="/health" shotdir="" dry=0 require_mcp=0 lint_only=0 emit_boot=0
while [ "$#" -gt 0 ]; do case "$1" in
  --repo) repo="$2"; shift 2;;
  --criteria) criteria="$2"; shift 2;;
  --url) url="$2"; shift 2;;
  --health) health="$2"; shift 2;;
  --screenshot-dir) shotdir="$2"; shift 2;;
  --dry-run) dry=1; shift;;
  --require-mcp) require_mcp=1; shift;;
  --lint-only) lint_only=1; shift;;
  --emit-boot-check) emit_boot=1; shift;;
  *) echo "web-ui-verify-unknown-arg: $1" >&2; exit 2;;
esac; done

if [ "$emit_boot" -eq 1 ]; then
cat <<'GO'
// boot-check (generated by web-ui-verify): curl 200 != frontend works.
func init() {
    idx, _ := embeddedFS.ReadFile("dist/index.html")
    s := string(idx)
    if !strings.Contains(s, "/assets/") || !strings.Contains(s, `id="root"`) {
        panic("web-ui boot-check: embedded dist is a placeholder (no /assets/ or id=\"root\") — rebuild the frontend")
    }
}
GO
exit 0
fi

DET="$(dirname "$0")/../../config/detect-web-stack.sh"
stack="$(bash "$DET" "$repo" 2>/dev/null || true)"
if [ -z "$stack" ] || [ "$stack" = not-a-web-app ]; then
  echo "web-ui-stack: not-a-web-app"; echo "reason: no web framework / index.html marker" ; exit 2
fi

# --- §6.4 lint (Chrome-only / no-Bash-interleave / screenshot-dir legal) ---
lint() {
  local browser="${SDLC_WEB_BROWSER:-chrome}"
  case "$browser" in chrome) ;; *) echo "lint: non-Chrome browser '$browser' forbidden (§6.4)"; return 6;; esac
  [ "${SDLC_WEB_BASH_INTERLEAVE:-0}" = 1 ] && { echo "lint: Bash interleaved during E2E (§6.4 forbidden)"; return 6; }
  if [ -n "$shotdir" ]; then
    case "$shotdir" in
      "$repo"|"$repo"/) echo "lint: screenshot dir is repo root (§6.4 forbidden)"; return 6;;
      docs/screenshots/*|*/.playwright-mcp|.playwright-mcp|.playwright-mcp/*) ;;
      *) echo "lint: screenshot dir '$shotdir' must be docs/screenshots/<topic> or .playwright-mcp"; return 6;;
    esac
  fi
  return 0
}
if ! lint; then exit 6; fi
[ "$lint_only" -eq 1 ] && { echo "web-ui-stack: $stack"; echo "lint: PASS"; exit 0; }

# --- contract parse (§5) — fail-closed exit 7 if absent/trivial; build_id-absent ⇒ UI-UNVERIFIED ---
[ -n "$criteria" ] || criteria="$repo/web-ui-verify.yaml"
contract_fail() { echo "web-ui-no-criteria: $1" >&2; exit 7; }
[ -f "$criteria" ] || contract_fail "missing $criteria (per-route success contract required)"

nroutes=$(yq -r '.routes | length' "$criteria" 2>/dev/null || echo 0)
case "$nroutes" in ''|0|null) contract_fail "$criteria has no routes";; esac

i=0; build_id=$(yq -r '.build_id // ""' "$criteria")
while [ "$i" -lt "$nroutes" ]; do
  psel=$(yq -r ".routes[$i].positive.selector // \"\"" "$criteria")
  ptxt=$(yq -r ".routes[$i].positive.text // \"\"" "$criteria")
  nneg=$(yq -r ".routes[$i].negative | length" "$criteria" 2>/dev/null || echo 0)
  [ -n "$psel" ] || contract_fail "route $i missing positive.selector"
  # trivial (re-G3 P0 fix): EITHER an empty/whitespace text (the verdict glob *""* matches ANY page —
  # vacuous positive ⇒ PASS on a blank page) OR a generic selector (matches any page) is fatal ALONE,
  # not only their conjunction. (The prior `gensel AND empty` let non-generic-selector + empty-text
  # slip → false-green on a blank #root.)
  case "$psel" in
    body|html|:root|'*'|'#root'|' '*|'') gensel=1;; *) gensel=0;;
  esac
  trimmed=$(printf '%s' "$ptxt" | tr -d '[:space:]')
  if [ -z "$trimmed" ]; then contract_fail "route $i positive.text empty/whitespace (vacuous — matches any page)"; fi
  if [ "$gensel" -eq 1 ]; then contract_fail "route $i generic positive.selector '$psel' (matches any page)"; fi
  case "$nneg" in ''|0|null) contract_fail "route $i has zero negative markers (>=1 required)";; esac
  i=$((i+1))
done

# --- MCP presence probe (§5) ---
mcp_present() {
  case "${SDLC_PLAYWRIGHT_MCP:-}" in 1) echo yes; return;; 0) echo no; return;; esac
  command -v claude >/dev/null 2>&1 || { echo no; return; }
  # portable bounded probe: GNU `timeout`, else macOS `gtimeout` (coreutils), else UNBOUNDED — macOS
  # ships neither (hard-constraint #5); the unbounded fallback is bounded only by claude's own timeout.
  local out to=""
  if command -v timeout >/dev/null 2>&1; then to=timeout
  elif command -v gtimeout >/dev/null 2>&1; then to=gtimeout; fi
  if [ -n "$to" ]; then out="$("$to" "${SDLC_MCP_PROBE_TIMEOUT:-45}" claude mcp list 2>/dev/null)" || { echo no; return; }
  else out="$(claude mcp list 2>/dev/null)" || { echo no; return; }; fi
  case "$out" in *playwright*Connected*|*chrome-devtools*Connected*) echo yes;; *) echo no;; esac
}
mcp="$(mcp_present)"

echo "web-ui-stack: $stack"
echo "mcp-present:  $mcp"

if [ "$dry" -eq 1 ]; then
  echo "# dry-run (no browser run). stack=$stack mcp=$mcp url=${url:-<unset>} health=$health"
  echo "criteria: $criteria"
  j=0; while [ "$j" -lt "$nroutes" ]; do
    echo "route: $(yq -r ".routes[$j].path" "$criteria")"; j=$((j+1))
  done
  exit 0
fi

if [ "$mcp" = no ]; then
  [ "$require_mcp" -eq 1 ] && { echo "verdict:      UI-UNVERIFIED"; echo "reason:       --require-mcp set but MCP absent"; exit 5; }
  echo "verdict:      UI-UNVERIFIED"
  echo "reason:       Playwright MCP absent — server-side checks only (WARN, not a block)"
  exit 0
fi
# build_id absent ⇒ freshness unprovable ⇒ UI-UNVERIFIED (re-G1 fix B), never PASS
if [ -z "$build_id" ]; then
  echo "verdict:      UI-UNVERIFIED"
  echo "reason:       contract has no build_id — build freshness unprovable (never PASS)"
  exit 0
fi
# evidence freshness (part 7) — cited evidence must be produced THIS run (mtime >= run-start), else exit 7
if [ -n "${SDLC_WEBUI_EVIDENCE:-}" ] && [ -n "${SDLC_RUN_TS:-}" ]; then
  # portable mtime: GNU `stat -c %Y` then BSD/macOS `stat -f %m` (date -r FILE is GNU-only — hard-constraint #5)
  emt=$(stat -c %Y "$SDLC_WEBUI_EVIDENCE" 2>/dev/null || stat -f %m "$SDLC_WEBUI_EVIDENCE" 2>/dev/null || echo 0)
  if [ "$emt" -lt "$SDLC_RUN_TS" ]; then echo "web-ui-stale-evidence: $SDLC_WEBUI_EVIDENCE older than run-start" >&2; exit 7; fi
fi

# verdict engine (deterministic source of truth over the browser facts; real reads = provider-agnostic ui-vision-judge / PENDING-VERIFY)
snap="${SDLC_WEBUI_SNAPSHOT:-}"; con="${SDLC_WEBUI_CONSOLE:-}"; net="${SDLC_WEBUI_NETWORK:-}"
dom_bid="${SDLC_WEBUI_DOM_BUILD_ID:-}"
verdict=PASS; reason="contract met, browser-verified"
i=0
while [ "$i" -lt "$nroutes" ]; do
  ptxt=$(yq -r ".routes[$i].positive.text // \"\"" "$criteria")
  # belt-and-suspenders (re-G3): an empty positive text is vacuous — `*""*` matches anything incl. a
  # blank page. The contract parse already exit-7s this, but never let it reach the glob.
  [ -z "$ptxt" ] && { verdict=FAIL; reason="empty positive text (vacuous — would match any page)"; break; }
  # 1 positive present
  case "$snap" in *"$ptxt"*) ;; *) verdict=FAIL; reason="positive text '$ptxt' absent (200 but not rendered)"; break;; esac
  # 2 negative absent
  nneg=$(yq -r ".routes[$i].negative | length" "$criteria"); j=0
  while [ "$j" -lt "$nneg" ]; do
    neg=$(yq -r ".routes[$i].negative[$j]" "$criteria")
    case "$snap" in *"$neg"*) verdict=FAIL; reason="negative marker present: $neg (placeholder/error rendered)"; break 2;; esac
    j=$((j+1))
  done
  i=$((i+1))
done
# 3 zero console-error (re-G3 S2: broadened beyond "error" — Uncaught/SEVERE/Refused/Failed-to-load.
#    Real browser_console_messages format normalization is PENDING-VERIFY.)
if [ "$verdict" = PASS ]; then case "$con" in
  *error*|*Error*|*ERROR*|*Uncaught*|*SEVERE*|*Refused*|*"Failed to load"*) verdict=FAIL; reason="console error present";;
esac; fi
# 4 zero failed-network 4xx/5xx (re-G3 S1: status token after a delimiter — " 404"/"[404]"/"=404"/":404"
#    — so it isn't missed when formatted without a leading space. Real format normalization is PENDING-VERIFY.)
if [ "$verdict" = PASS ]; then case "$net" in
  *' '[45][0-9][0-9]*|*'['[45][0-9][0-9]*|*'='[45][0-9][0-9]*|*':'[45][0-9][0-9]*) verdict=FAIL; reason="failed asset request (4xx/5xx)";;
esac; fi
# 5 build fresh (DOM build_id == contract build_id)
if [ "$verdict" = PASS ] && [ "$dom_bid" != "$build_id" ]; then verdict=FAIL; reason="stale build: DOM build_id '$dom_bid' != contract '$build_id'"; fi

echo "verdict:      $verdict"
echo "reason:       $reason"
echo "evidence:     reports/runs/${SDLC_RUN_TS:-pending}_web-ui/verdict.txt"
# vision annotation (v0.30 ui-vision-judge) — SOFT signal, rides ALONGSIDE the verdict, NEVER feeds it.
# The deterministic engine above (lines 140-175, byte-frozen vs v0.29.0 — tests/golden/) is the source
# of truth; this only ANNOTATES and can never flip PASS↔FAIL.
if [ -n "${SDLC_WEBUI_VISION_ANNOTATION:-}" ]; then
  echo "vision_annotation: ${SDLC_WEBUI_VISION_ANNOTATION}"
  case "${SDLC_WEBUI_VISION_ANNOTATION}" in
    *'"looks_ok":false'*) [ "$verdict" = PASS ] && echo "note:         WARN vision flags possible visual issue (does not change verdict)";;
  esac
fi
[ "$verdict" = PASS ] && exit 0 || exit 3
