#!/usr/bin/env bash
# emit.sh — deterministic stack-config-driven CI yaml emitter (v0.16).
# Reads config/stack-<name>.yaml for exact build/lint/test commands; emits the 5 mandatory
# stages (build/lint/test/security_scan/publish). NEVER inlines plaintext secrets — only
# ${{ secrets.X }} / $ENV placeholders (CLAUDE.md §1.4). Commands go in YAML block scalars
# (`run: |`) so embedded quotes in a config command can't malform the yaml (G2 fold-in).
# Complements cicd-designer (LLM design + CD strategy + rollback runbook). Zero LLM. bash-3.2-safe.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
CONFIG="${SDLC_CONFIG_DIR:-$HERE/../../config}"

stack="" platform="github" out=""
while [ "$#" -gt 0 ]; do case "$1" in
  --stack) stack="$2"; shift 2;;
  --platform) platform="$2"; shift 2;;
  --out) out="$2"; shift 2;;
  *) shift;;
esac; done

[ -n "$stack" ] || { echo "usage: emit.sh --stack <name> [--platform github|generic] [--out <f>]" >&2; exit 2; }
case "$stack" in *[!a-z0-9-]*|'') echo "emit-bad-stack: $stack" >&2; exit 2;; esac
case "$platform" in github|generic) : ;; *) echo "emit-bad-platform: $platform" >&2; exit 2;; esac

cfg="$CONFIG/stack-$stack.yaml"
[ -f "$cfg" ] || cfg="$CONFIG/stack-generic.yaml"      # unknown stack → generic fallback
[ -f "$cfg" ] || { echo "emit-no-config: $cfg" >&2; exit 2; }

field() { yq -r ".$1 // \"\"" "$cfg"; }
build=$(field build); lint=$(field lint); test_all=$(field test_all)
if [ -z "$build" ] || [ -z "$lint" ] || [ -z "$test_all" ]; then
  echo "emit-incomplete-config: $cfg (need build/lint/test_all)" >&2; exit 2
fi

case "$stack" in
  rust) scan="cargo audit";;
  ts) scan="npm audit --audit-level=high";;
  python) scan="pip-audit";;
  go) scan="govulncheck ./...";;
  *) scan="echo 'TODO: configure a security scanner for this stack'";;
esac

emit_github() {
cat <<YAML
# Generated by /sdlc:pipeline (deterministic; commands from config/stack-$stack.yaml).
# Secrets: reference \${{ secrets.NAME }} only — never inline plaintext (CLAUDE.md §1.4).
# Branch protection: main requires PR + all jobs green. Production deploy (canary/blue-green)
# + rollback runbook: add via /sdlc:cicd (cicd-designer).
name: sdlc-ci
on:
  push: { branches: [main, master] }
  pull_request: { branches: [main, master] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          $build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          $lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          $test_all
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          $scan
  publish:
    needs: [build, lint, test, security_scan]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "publish (token via \${{ secrets.PUBLISH_TOKEN }})"
YAML
}

emit_generic() {
cat <<YAML
# Generated by /sdlc:pipeline (platform-neutral; commands from config/stack-$stack.yaml).
# Secrets: reference \$SECRET_NAME env (set in CI secret store) — never inline plaintext (§1.4).
stages: [build, lint, test, security_scan, publish]
build:
  script: |
    $build
lint:
  script: |
    $lint
test:
  script: |
    $test_all
security_scan:
  script: |
    $scan
publish:
  script: |
    echo "publish (token via \$PUBLISH_TOKEN env)"
  when: on_success
  only: [main]
YAML
}

if [ "$platform" = "github" ]; then yaml=$(emit_github); else yaml=$(emit_generic); fi

# self-check: all 5 mandatory stages present (cicd-designer rule 1 — never skip security_scan).
# Use case-glob, NOT `printf | grep -q`: under `set -o pipefail`, grep -q matching early closes
# the pipe → printf SIGPIPEs → pipeline exits 141 → false "missing-stage" (a real flake fixed here).
for s in build lint test security_scan publish; do
  case "$yaml" in
    *"$s"*) : ;;
    *) echo "pipeline-missing-stage: $s" >&2; exit 2 ;;
  esac
done

if [ -n "$out" ]; then
  mkdir -p "$(dirname "$out")"
  printf '%s\n' "$yaml" > "$out"
  echo "emitted=$out stack=$stack platform=$platform"
else
  printf '%s\n' "$yaml"
fi
